language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
before_script:
- python manage.py migrate
script:
- black .
- flake8 .
- coverage run --source="." manage.py test
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "T3jv1HumVASv3x/XoksWRh0xl87iMWDmgnH0hFQr8cwnO9l5bt9QqGgfkQw+xUIGP74vabmZvrTJPQx4D70YWFlU7tG3vXIVciWLJgetjZw/ZVfyiJHelWGXb/PakziJGH6m5aWP22D+zOF7Xb/CUY5ByQ7NLPxM5rC7+tZUtv1ZhmJS4ZUSSItSzWYu9Jk+pL7tSNbPjvuaT9E+zr+jSs/9oOZoSGQNSiF7eRQ06CUF8WN43OZeJwaSLud5+3bMFvzmpsv+c0h5InltQOJ+n0LGle8jnvY2nWzfBexKLU3suUMsGlGv2PzPk6Psd9VUee1fM8jrc5XfYMPX4xFI0T0DoL1ayUEiEvJUB99eImRhMvdQVn0S0T2K9OCyvZD8GFEkkrTXLED0TTTE3AjtNVyD/u9hdnaMUnYCZT5QzoipiCAEobC9+A9gJenF9EZIEwmm6ALhukQPpHPz6M0gtgRfXapwuz2kmcFR7bSv+epRl1RhY9ZaZVm+stC7odlUqDy6O/cHyKTI32bykEIZwcuElmYCAOpN3mNPR/C+z0BzsLsUZRwC8bO49CcuWD7+Pla7BLWxWcuSdwfXrUt2xVtnXPJDuTB2jxZtyxjUo00rSWFQGV7SRA1efpAWm6kfPQS+MDNPtvO7p2lC5KDKx8qkLD85YYJNUwNwDZPLczE="
  secret_access_key:
    secure: "hWI32E5AdoWeYfAb748n0WjLVAvUt8kzH5EU5sQiNKFnCE+nsV/ZVGF79XvmXqSACfQra0tyHTy6e3cyA1K8z1gpxb3icpV/6OGWfrUjdmAG7ZVUG3Ncl7swjqg1VlGWt5nHjA9H7y55w2zFbFsGe/+UL0vC+iFjPdG/zv5dGDpxXj7wY92wudwHyyTmVFmiMpc6CBiqbGjfAclmVid16I521DbUZwBxjtNt0RhXQP8+2tAgFeVwHyDd9gnew++ULX4pnF7Ls+fBfORLA+DIJnN6u6NAfsM19LZYg7bV4Vg2lQVoOy1r/TjDyKOS4elPhZMeesg7mpc0Z6eH+JenyqoIEtIpgoVLs/jyYXCouJGhS+pg6iBXqzmgm3MxQhn6H1+cxKugt5pESAuwaxnAHhB6IQHlwqhZenbWfT+PudZuY23aPUrXGqMzVdwOqd95O5WQsn9HJxWCHsrjiU2V4TYgmBULF0/Uhbqgp07lbmrYzHmnO88J7NY3CiP6sIZlJApOZ4bLxZ/gQO01nJJMU4l6YjDUAubSuK2o9Z/s2DoAy4o/CyPnH+UAROvCx33z2donoS4yHqKH/JlRNP7KdZ3+GYpbizYQrnnRl34IZr+VwCQL1JAZoYmh9wa2K3Cb3os/IAwQmlwCXWtIyiNCjcQy8I5FommzWodMEGcFIU0="
  region: "us-east-1"
  app: "django_tutorial_rs8117"
  env: "django-tutorial-env"
  bucket_name: "elasticbeanstalk-us-east-1-863036555906"
  on:
    repo: ramanarayanan-98/swe1-app
    branch: main
